## Task 2: Create 3 DataFrames using Dictionary

In [1]:
import pandas as pd

### 1. List in Dictionary
 allows duplicate
- allows mixed types in the list
- 1 Dimensional
- mutable --> the values can be changed by accessing the index value
- can access data via indexing
  * forward accessing starts with index 0
  * backward accessing starts with index -1

In [4]:
student_grade_details = {"Name":["Viyaan","Amritha","Bala","Rio"],
                         "class":[10,10,10,10],
                         "City":["chennai","Theni","Coimbatore","Theni"],
                         "Grade":["A","A","C","B"],
                         "Result":["Pass","Pass","Fail","Pass"]
                        }
Student_table=pd.DataFrame(student_grade_details)

      Name  class        City Grade Result
0   Viyaan     10     chennai     A   Pass
1  Amritha     10       Theni     A   Pass
2     Bala     10  Coimbatore     C   Fail
3      Rio     10       Theni     B   Pass

### 2. Tuple in Dictionary
1. 1d
2. allow duplicate
3. allow all datatype
4. indexing and slicing possible
5. immutable - values cannot be changed once assigned

In [27]:
restaurant_menu = {"Item_no":(1,2,3,1),
                   "Food_Items": ("Biryani", "Pizza", "Burger","Biryani"),
                   "Price":("$30","$9.99","$8.99","")
                  }

menu_table = pd.DataFrame(restaurant_menu)
menu_table

   Item_no Food_Items  Price
0        1    Biryani    $30
1        2      Pizza  $9.99
2        3     Burger  $8.99
3        1    Biryani

### 3. Set in Dictionary

* 1D
* indexing and silicing is not applicable
* mutable
* allows all kinda datatypes
* set cannot be directly converted into rows and columns using DataFrame.
   - set has to be convereted to list or tuple before converting it to table.

In [36]:
icecream_shop = {
                 "Icecream_ flavors":{"strawberry","chocolate","Butter scotch"},
                 "Quantity":{"Small","Medium","Large"},
                 "Topping":{"Choco-chip","dry-fruits","maple-syrup"}
                }
                


pd.DataFrame(list(icecream_shop)) # displays the key mentioned

                   0
0  Icecream_ flavors
1           Quantity
2            Topping

In [34]:
icecream_shop = {
                 "Icecream_ flavors":{"strawberry","chocolate","Butter scotch"},
                 "Quantity":{"Small","Medium","Large"},
                 "Topping":{"Choco-chip","dry-fruits","maple-syrup"}
                }
                


pd.DataFrame(list(icecream_shop["Icecream_ flavors"])) # displays the value of the key mentioned

               0
0      chocolate
1  Butter scotch
2     strawberry

In [40]:
icecream_shop = {
                 "Icecream_ flavors":{"strawberry","chocolate","Butter scotch"},
                 "Quantity":{"Small","Medium","Large"},
                 "Topping":{"Choco-chip","dry-fruits","maple-syrup"}
                }
                


# converting entire set dict to list dict so pandas can convert to row and columns

icecreamshop_menu = {
                     key : list(value) for key, value in icecream_shop.items()
                    }

pd.DataFrame(icecreamshop_menu)

  Icecream_ flavors Quantity      Topping
0         chocolate    Small   dry-fruits
1     Butter scotch    Large   Choco-chip
2        strawberry   Medium  maple-syrup

In [39]:
icecream_shop.items()

dict_items([('Icecream_ flavors', {'chocolate', 'Butter scotch', 'strawberry'}), ('Quantity', {'Small', 'Large', 'Medium'}), ('Topping', {'dry-fruits', 'Choco-chip', 'maple-syrup'})])