In [1]:
import pandas as pd

In [2]:
customer_data = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
customer_data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
customer_data.shape

(3900, 18)

In [8]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
customer_data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
customer_data.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [18]:
customer_data['Review Rating']=customer_data.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.mean()))

In [19]:
customer_data.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [30]:
customer_data.columns = customer_data.columns.str.lower()
customer_data.columns = customer_data.columns.str.replace(" ","_")
customer_data.rename(columns={'purchase_amount_(usd)':'purchase_amount'},inplace=True)
customer_data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [31]:
labels = ['Young Adult','Adult','Middle Aged','Senior']
customer_data['age_group'] = pd.qcut(customer_data['age'],q=4,labels=labels)

In [32]:
customer_data

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle Aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle Aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle Aged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,Adult
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,Middle Aged
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,Middle Aged
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,Adult
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,Middle Aged

In [35]:
customer_data.groupby('age_group')['age'].count()

C:\Users\amrit\AppData\Local\Temp\ipykernel_26840\2732247403.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_data.groupby('age_group')['age'].count()

age_group
Young Adult    1028
Adult           942
Middle Aged     986
Senior          944
Name: age, dtype: int64

In [45]:
age_check =pd.DataFrame(customer_data['age'].value_counts().sort_index())
age_check

     count
age
18      69
19      81
20      62
21      69
22      66
23      71
24      68
25      85
26      69
27      83
28      79
29      76
30      71
31      79
32      82
33      63
34      68
35      72
36      74
37      77
38      70
39      68
40      72
41      86
42      80
43      79
44      51
45      72
46      76
47      71
48      68
49      84
50      83
51      72
52      73
53      70
54      83
55      73
56      74
57      87
58      81
59      75
60      65
61      65
62      83
63      75
64      73
65      72
66      71
67      54
68      75
69      88
70      67

In [47]:
age_check['count'].idxmax()

np.int64(69)

In [50]:
age_check['count'].max()

np.int64(88)

In [46]:
age_check.loc[age_check['count'] == age_check['count'].max()]

     count
age
69      88

In [37]:
pd.qcut(customer_data['age'], q=4).unique()

[(44.0, 57.0], (17.999, 31.0], (57.0, 70.0], (31.0, 44.0]]
Categories (4, interval[float64, right]): [(17.999, 31.0] < (31.0, 44.0] < (44.0, 57.0] < (57.0, 70.0]]

In [52]:
customer_data['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [53]:

frequency_mapping = {'Fortnightly':14,
                     'Weekly':7,
                     'Annually':365,
                     'Quarterly':90,
                     'Bi-Weekly':14,
                     'Monthly':30,
                     'Every 3 Months':90}

customer_data['purchase_frequency_days'] = customer_data['frequency_of_purchases'].map(frequency_mapping)

In [54]:
customer_data[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [56]:
customer_data[['discount_applied','promo_code_used']] #

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [60]:
(customer_data['discount_applied']==customer_data['promo_code_used']).all()

np.True_

In [61]:
del customer_data['promo_code_used']

In [62]:
customer_data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [63]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp310-cp310-win_amd64.whl (2.8 MB)
     ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
      --------------------------------------- 0.0/2.8 MB 991.0 kB/s eta 0:00:03
     -- ------------------------------------- 0.1/2.8 MB 1.7 MB/s eta 0:00:02
     ------- -------------------------------- 0.5/2.8 MB 3.5 MB/s eta 0:00:01
     ------------- -------------------------- 0.9/2.8 MB 5.0 MB/s eta 0:00:01
     ------------------- -------------------- 1.4/2.8 MB 5.8 MB/s eta 0:00:01
     ------------------------- -------------- 1.7/2.8 MB 6.1 MB/s eta 0:00:01
     ------------------------------- -------- 2.2/2.8 MB 6.5 MB/s eta 0:00:01
     ------------------------------------ --- 2.5/2.8 MB 6.8 MB/s eta 0:00:01
     ---------------------------------------- 2.8/2.8 MB 6.5 MB/s eta 0:00:00
Requirement already satisfied: sqlalchemy in c:\users\amrit\appdata\local\programs\python\python310\lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\users\amrit\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\amrit\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [68]:
# Step 1: Connect to PostgreSQL
# Replace with your actual details
from sqlalchemy import create_engine

username = "postgres"        # default user
password = "root"        # password you set during installation
host = "localhost"           # if running locally
port = "5432"                # default PostgreSQL port
database = "customer_behavior"  # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"      # choose any table name
customer_data.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'")

Data successfully loaded into table 'customer' in database 'customer_behavior'

In [71]:
customer_data[customer_data['previous_purchases']==1]

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
104,105,55,Male,Sunglasses,Accessories,24,New Hampshire,L,Pink,Spring,4.4,Yes,2-Day Shipping,Yes,1,PayPal,Monthly,Middle Aged,30
157,158,36,Male,Hat,Accessories,68,Vermont,S,Yellow,Fall,3.0,Yes,Next Day Air,Yes,1,Bank Transfer,Fortnightly,Adult,14
187,188,19,Male,Shoes,Footwear,94,Georgia,S,Purple,Spring,3.3,Yes,Store Pickup,Yes,1,Bank Transfer,Bi-Weekly,Young Adult,14
319,320,47,Male,Shorts,Clothing,74,Maine,XL,White,Spring,2.6,Yes,Standard,Yes,1,Cash,Every 3 Months,Middle Aged,90
355,356,37,Male,Jewelry,Accessories,42,Oregon,XL,Magenta,Fall,4.1,Yes,2-Day Shipping,Yes,1,PayPal,Every 3 Months,Adult,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3728,3729,62,Female,Jacket,Outerwear,31,Vermont,L,Red,Winter,3.0,No,Standard,No,1,Debit Card,Annually,Senior,365
3791,3792,40,Female,Sunglasses,Accessories,51,Texas,M,Gray,Spring,3.7,No,Store Pickup,No,1,Venmo,Weekly,Adult,7
3802,3803,70,Female,Scarf,Accessories,72,Illinois,S,Turquoise,Spring,3.2,No,2-Day Shipping,No,1,Bank Transfer,Monthly,Senior,30
3864,3865,55,Female,T-shirt,Clothing,99,Wyoming,S,Blue,Winter,4.9,No,Express,No,1,Debit Card,Fortnightly,Middle Aged,14
3887,3888,40,Female,Shirt,Clothing,34,Kansas,M,Charcoal,Spring,2.7,No,Express,No,1,Credit Card,Quarterly,Adult,90