In [51]:
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score,KFold
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import warnings
warnings.filterwarnings("ignore")

In [2]:
wine_data = pd.DataFrame(data=load_wine().data,columns=load_wine().feature_names)

In [3]:
wine_data["Target"] = load_wine().target

In [4]:
wine_data

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,Target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [5]:
wine_data["Target"].value_counts()

Target
1    71
0    59
2    48
Name: count, dtype: int64

In [6]:
wine_data.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
Target                          0
dtype: int64

In [7]:
wine_data.dtypes

alcohol                         float64
malic_acid                      float64
ash                             float64
alcalinity_of_ash               float64
magnesium                       float64
total_phenols                   float64
flavanoids                      float64
nonflavanoid_phenols            float64
proanthocyanins                 float64
color_intensity                 float64
hue                             float64
od280/od315_of_diluted_wines    float64
proline                         float64
Target                            int64
dtype: object

In [8]:
X=wine_data.drop("Target",axis=1)
X

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [9]:
y = wine_data["Target"]

In [42]:
std_scalar = StandardScaler()
scalar_X=std_scalar.fit_transform(X)
pd.DataFrame(scalar_X)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.518613,-0.562250,0.232053,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009
1,0.246290,-0.499413,-0.827996,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242
2,0.196879,0.021231,1.109334,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148
3,1.691550,-0.346811,0.487926,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574
4,0.295700,0.227694,1.840403,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.876275,2.974543,0.305159,0.301803,-0.332922,-0.985614,-1.424900,1.274310,-0.930179,1.142811,-1.392758,-1.231206,-0.021952
174,0.493343,1.412609,0.414820,1.052516,0.158572,-0.793334,-1.284344,0.549108,-0.316950,0.969783,-1.129518,-1.485445,0.009893
175,0.332758,1.744744,-0.389355,0.151661,1.422412,-1.129824,-1.344582,0.549108,-0.422075,2.224236,-1.612125,-1.485445,0.280575
176,0.209232,0.227694,0.012732,0.151661,1.422412,-1.033684,-1.354622,1.354888,-0.229346,1.834923,-1.568252,-1.400699,0.296498
177,1.395086,1.583165,1.365208,1.502943,-0.262708,-0.392751,-1.274305,1.596623,-0.422075,1.791666,-1.524378,-1.428948,-0.595160

In [43]:
X_train, X_test, y_train, y_test=train_test_split(scalar_X,y,test_size=0.20,random_state=42,shuffle=True,stratify=y)

## KNN Algorithm

In [44]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred_train = knn.predict(X_train)
print("Accuracy Score:",accuracy_score(y_train,y_pred_train))

Accuracy Score: 0.9647887323943662

In [45]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred_train = knn.predict(X_train)
print("Accuracy Score:",accuracy_score(y_train,y_pred_train))

Accuracy Score: 0.9788732394366197

In [46]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)
y_pred_train = knn.predict(X_train)
print("Accuracy Score:",accuracy_score(y_train,y_pred_train))

Accuracy Score: 0.971830985915493

In [47]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train,y_train)
y_pred_train = knn.predict(X_train)
print("Accuracy Score:",accuracy_score(y_train,y_pred_train))

Accuracy Score: 0.9647887323943662

## How to choose the optimal number of neighbours

In [49]:
best_accuracy_score = 0 
best_n=0
for n in range(3,52):
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train,y_train)
    y_pred_train = knn.predict(X_train)
   
    current_ac_score = accuracy_score(y_train,y_pred_train)

    if(current_ac_score>best_accuracy_score):
        best_accuracy_score=current_ac_score
        best_n=n

print("N:",best_n,"\nAccuracy Score:",best_accuracy_score)

N: 5
Accuracy Score: 0.9788732394366197

In [86]:
best_score=0
bestof_n = 0

fold = KFold(n_splits=10,shuffle=True,random_state=42)

for n in range(3,52,2):
    
    knn=KNeighborsClassifier(n_neighbors=n)
    
    cv=cross_val_score(estimator=knn,X=scalar_X,y=y,cv=fold)
    
    current_score = np.mean(cv)

    if(current_score>best_score):
        best_score=current_score
        bestof_n=n

print("Score:",best_score,"\nBest_n:",bestof_n)

Score: 0.9777777777777779
Best_n: 11

In [87]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_neighbors': list(range(3,52,2))}

knn = KNeighborsClassifier()

grid = GridSearchCV(knn, param_grid, cv=fold)
grid.fit(scalar_X, y)

print(grid.best_score_)
print(grid.best_params_)

0.9777777777777779
{'n_neighbors': 11}

Cross‑Validation is used to evaluate a model’s performance.
GridSearchCV is used to tune hyperparameters, and it uses CV internally.
So CV = evaluation, GridSearchCV = tuning + evaluation.